# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: "/home/bingxing2/home/scx7124/asr_workspace/fairseq/examples/wav2vec/tensorboard/02_multilingual_10_pretrain_with_gradacc"

checkpoint:
  best_checkpoint_metric: 'loss'
  save_interval_updates: 1000
  keep_interval_updates: 1
  keep_best_checkpoints: 3
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining
  data: /home/bingxing2/home/scx7124/asr_workspace/fairseq/examples/wav2vec/data
  max_sample_size: 250000
  min_sample_size: 32000
  normalize: false

dataset:
  num_workers: 6
  max_tokens: 7000000
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  distributed_world_size: 4
  ddp_backend: legacy_ddp
  distributed_port: 29501

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity","temp"]
  loss_weights: [0.1, 10]

optimization:
  update_freq: [4]
  max_update: 1000000
  lr: [0.0001]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 8000

model:
  _name: wav2vec2
  quantize_targets: true
  final_dim: 256
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  feature_grad_mult: 0.1
  encoder_embed_dim: 768
